# Generated by Django 5.2.1 on 2025-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('UNS', 'Unsubscribed'), ('PEN', 'Pending Confirmation')], default='ACT', max_length=3, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
