# Generated by Django 5.2.1 on 2025-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_forms', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('waist_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waist Circumference (cm)')),
                ('hip_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hip Circumference (cm)')),
                ('chest_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chest Circumference (cm)')),
                ('arm_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Arm Circumference (cm)')),
                ('thigh_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Thigh Circumference (cm)')),
                ('neck_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Neck Circumference (cm)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='body_measurements/', verbose_name='Full-body Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Body Measurements',
                'verbose_name_plural': 'Body Measurements',
                'ordering': ['-created_at'],
            },
        ),
    ]
