# Generated by Django 5.2.1 on 2025-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='arm_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Arm Circumference (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='body_photo',
            field=models.ImageField(blank=True, null=True, upload_to='body_measurements/', verbose_name='Full-body Photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chest_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chest Circumference (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hip_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hip Circumference (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neck_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Neck Circumference (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='thigh_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Thigh Circumference (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waist Circumference (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
    ]
