# Generated by Django 5.2.1 on 2025-05-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_arm_circumference_profile_body_photo_and_more'),
        ('diet_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diet_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='diet_plans.dietplan', verbose_name='Selected Diet Plan'),
        ),
    ]
