# Generated by Django 5.2.1 on 2025-05-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_diet_plan'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_users', to='workouts.workoutplan', verbose_name='Selected Workout Plan'),
        ),
    ]
