# Generated by Django 5.2.1 on 2025-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Recipe Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('BF', 'Breakfast'), ('LN', 'Lunch'), ('DN', 'Dinner'), ('SN', 'Snack'), ('DS', 'Dessert'), ('BV', 'Beverage'), ('VG', 'Vegetarian'), ('VN', 'Vegan'), ('KT', 'Keto'), ('LC', 'Low Carb'), ('HP', 'High Protein'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Category')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Preparation Time (minutes)')),
                ('cooking_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cooking Time (minutes)')),
                ('servings', models.PositiveIntegerField(blank=True, null=True, verbose_name='Servings')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories per Serving')),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Protein (g)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Carbs (g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Fat (g)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/images/', verbose_name='Recipe Image')),
                ('video_url', models.URLField(blank=True, help_text='URL to a video of the recipe (e.g., YouTube)', max_length=255, null=True, verbose_name='Video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
