# Generated by Django 5.2.1 on 2025-05-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('WL', 'Weight Loss'), ('MG', 'Muscle Gain'), ('MT', 'Maintenance'), ('VG', 'Vegetarian'), ('VN', 'Vegan'), ('KT', 'Keto'), ('LC', 'Low Carb'), ('HP', 'High Protein'), ('BL', 'Balanced')], default='BL', max_length=2, verbose_name='Category')),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='Duration (weeks)')),
                ('calories_per_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories per Day')),
                ('protein_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Protein %')),
                ('carbs_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carbs %')),
                ('fat_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fat %')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diet_plans/', verbose_name='Plan Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diet Plan',
                'verbose_name_plural': 'Diet Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(verbose_name='Week Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Week Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='diet_plans.dietplan')),
            ],
            options={
                'verbose_name': 'Diet Plan Week',
                'verbose_name_plural': 'Diet Plan Weeks',
                'ordering': ['diet_plan', 'week_number'],
                'unique_together': {('diet_plan', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='DietPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Day of Week')),
                ('meal_type', models.CharField(choices=[('BF', 'Breakfast'), ('LN', 'Lunch'), ('DN', 'Dinner'), ('SN', 'Snack'), ('PW', 'Pre-Workout'), ('PT', 'Post-Workout')], max_length=2, verbose_name='Meal Type')),
                ('name', models.CharField(max_length=100, verbose_name='Meal Name')),
                ('description', models.TextField(verbose_name='Meal Description')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('preparation', models.TextField(blank=True, null=True, verbose_name='Preparation Instructions')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories')),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Protein (g)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Carbs (g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Fat (g)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diet_plans/meals/', verbose_name='Meal Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet_plans.dietplanweek')),
            ],
            options={
                'verbose_name': 'Diet Plan Meal',
                'verbose_name_plural': 'Diet Plan Meals',
                'ordering': ['week', 'day_of_week', 'meal_type'],
                'unique_together': {('week', 'day_of_week', 'meal_type')},
            },
        ),
    ]
