# Generated by Django 5.2.1 on 2025-05-17 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Exercise Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('body_part', models.CharField(choices=[('FB', 'Full Body'), ('UB', 'Upper Body'), ('LB', 'Lower Body'), ('CR', 'Core'), ('AR', 'Arms'), ('CH', 'Chest'), ('BK', 'Back'), ('SH', 'Shoulders'), ('LG', 'Legs'), ('GL', 'Glutes'), ('CV', 'Calves'), ('BI', 'Biceps'), ('TR', 'Triceps'), ('AB', 'Abs')], default='FB', max_length=2, verbose_name='Body Part')),
                ('difficulty', models.CharField(choices=[('BG', 'Beginner'), ('IM', 'Intermediate'), ('AD', 'Advanced'), ('EX', 'Expert')], default='BG', max_length=2, verbose_name='Difficulty')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='Tips')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/exercises/', verbose_name='Exercise Image')),
                ('video_url', models.URLField(blank=True, help_text='URL to a video demonstrating the exercise', max_length=255, null=True, verbose_name='Video URL')),
                ('equipment_needed', models.BooleanField(default=False, verbose_name='Equipment Needed')),
                ('equipment_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipment Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Plan Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('ST', 'Strength Training'), ('CD', 'Cardio'), ('FL', 'Flexibility'), ('HI', 'High Intensity Interval Training'), ('EN', 'Endurance'), ('BL', 'Balance'), ('YG', 'Yoga'), ('PL', 'Pilates'), ('CF', 'CrossFit'), ('BW', 'Bodyweight'), ('WL', 'Weightlifting'), ('FN', 'Functional Training'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Category')),
                ('difficulty', models.CharField(choices=[('BG', 'Beginner'), ('IM', 'Intermediate'), ('AD', 'Advanced'), ('EX', 'Expert')], default='BG', max_length=2, verbose_name='Difficulty')),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='Duration (weeks)')),
                ('sessions_per_week', models.PositiveIntegerField(default=3, verbose_name='Sessions per Week')),
                ('minutes_per_session', models.PositiveIntegerField(default=30, verbose_name='Minutes per Session')),
                ('goal', models.TextField(blank=True, null=True, verbose_name='Goal')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/plans/', verbose_name='Plan Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Day Number')),
                ('name', models.CharField(max_length=100, verbose_name='Day Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rest_day', models.BooleanField(default=False, verbose_name='Rest Day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'Workout Day',
                'verbose_name_plural': 'Workout Days',
                'ordering': ['workout_plan', 'day_number'],
                'unique_together': {('workout_plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='UserWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workouts', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'User Workout',
                'verbose_name_plural': 'User Workouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Sets')),
                ('reps', models.CharField(default='10', max_length=50, verbose_name='Reps')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Rest (seconds)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday')),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workout Exercises',
                'ordering': ['workout_day', 'order'],
                'unique_together': {('workout_day', 'exercise', 'order')},
            },
        ),
    ]
