# Generated by Django 5.2.1 on 2025-05-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('video_url', models.URLField(help_text='URL to the video tutorial (e.g., YouTube)', max_length=255, verbose_name='Video URL')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='workouts/videos/thumbnails/', verbose_name='Thumbnail')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tutorials', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'Video Tutorial',
                'verbose_name_plural': 'Video Tutorials',
                'ordering': ['workout_plan', 'order'],
                'unique_together': {('workout_plan', 'order')},
            },
        ),
    ]
