# Generated by Django 5.2.1 on 2025-05-17 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_videotutorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('video_url', models.URLField(help_text='URL to the video (e.g., YouTube)', max_length=255, verbose_name='Video URL')),
                ('category', models.CharField(choices=[('WO', 'Workout'), ('NU', 'Nutrition'), ('MO', 'Motivation'), ('TE', 'Technique'), ('ST', 'Stretching'), ('RE', 'Recovery'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Category')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='workouts/saved_videos/thumbnails/', verbose_name='Thumbnail')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Personal Notes')),
                ('source_type', models.CharField(choices=[('tutorial', 'Workout Tutorial'), ('external', 'External Video'), ('custom', 'Custom Upload')], default='external', max_length=20, verbose_name='Source Type')),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='ID of the source video if from a tutorial', null=True, verbose_name='Source ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Video',
                'verbose_name_plural': 'Saved Videos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video_url')},
            },
        ),
    ]
